import type { BillingPlanDefinition, LinkPackDefinition, SubscriptionPlanId } from './types';

export const billingPlans: BillingPlanDefinition[] = [
  {
    id: 'free',
    name: 'Free',
    badge: 'Explore the product',
    usd: '₹0',
    cadence: '/month',
    seats: '1 user',
    cta: 'Start free',
    accent: 'rgba(255,255,255,0.08)',
    description:
      'Best for trying branded links and basic reporting before you commit to a paid plan.',
    features: [
      '10 new links / month',
      '1 shared short domain',
      '30-day analytics',
      'Basic QR exports',
      'Community support',
    ],
    featured: false,
    monthlyLinkLimit: 10,
    trackedClicksLabel: '500',
    customDomainsLabel: '—',
    analyticsRetentionLabel: '30 days',
  },
  {
    id: 'starter',
    name: 'Starter',
    badge: 'For casual users',
    usd: '₹99',
    cadence: '/month',
    seats: '1 user',
    cta: 'Get Starter',
    accent: 'linear-gradient(135deg, #64748b, #475569)',
    description:
      'Perfect if you only need ~100 links a month. No overcommitting — just pay a little and get what you need.',
    features: [
      '100 new links / month',
      '5K tracked clicks',
      '1 shared short domain',
      '60-day analytics',
      'Basic QR exports',
    ],
    featured: false,
    monthlyLinkLimit: 100,
    trackedClicksLabel: '5K',
    customDomainsLabel: '—',
    analyticsRetentionLabel: '60 days',
  },
  {
    id: 'launch',
    name: 'Launch',
    badge: 'Most popular',
    usd: '₹399',
    cadence: '/month',
    seats: '2 users',
    cta: 'Choose Launch',
    accent: 'linear-gradient(135deg, #f59e0b, #ef4444)',
    description:
      'Ideal for solo founders and small teams who need branded links, a custom domain, and solid analytics at a low price.',
    features: [
      '500 new links / month',
      '25K tracked clicks',
      '1 custom domain',
      '90-day analytics',
      'UTM builder + CSV exports',
    ],
    featured: true,
    monthlyLinkLimit: 500,
    trackedClicksLabel: '25K',
    customDomainsLabel: '1',
    analyticsRetentionLabel: '90 days',
  },
  {
    id: 'growth',
    name: 'Growth',
    badge: 'For growing teams',
    usd: '₹799',
    cadence: '/month',
    seats: '5 users',
    cta: 'Choose Growth',
    accent: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    description:
      'Step up to 2,000 links, deeper analytics, and team collaboration — still at a price that feels fair.',
    features: [
      '2K new links / month',
      '100K tracked clicks',
      '1-year analytics retention',
      '3 custom domains',
      'API + webhook access',
    ],
    featured: false,
    monthlyLinkLimit: 2000,
    trackedClicksLabel: '100K',
    customDomainsLabel: '3',
    analyticsRetentionLabel: '1 year',
  },
  {
    id: 'scale',
    name: 'Scale',
    badge: 'For agencies & power users',
    usd: '₹2,399',
    cadence: '/month',
    seats: '10 users',
    cta: 'Choose Scale',
    accent: 'linear-gradient(135deg, #06b6d4, #0284c7)',
    description:
      'High-volume link management with A/B testing, priority support, and 10 custom domains for fast-moving teams.',
    features: [
      '10K new links / month',
      '500K tracked clicks',
      '2-year analytics retention',
      '10 custom domains',
      'A/B testing + priority support',
    ],
    featured: false,
    monthlyLinkLimit: 10000,
    trackedClicksLabel: '500K',
    customDomainsLabel: '10',
    analyticsRetentionLabel: '2 years',
  },
  {
    id: 'pro',
    name: 'Pro',
    badge: 'For large-scale operations',
    usd: '₹6,499',
    cadence: '/month',
    seats: '20 users',
    cta: 'Choose Pro',
    accent: 'linear-gradient(135deg, #10b981, #059669)',
    description:
      'Up to 100,000 links per month for large campaigns, marketing agencies, and high-traffic platforms.',
    features: [
      '100K new links / month',
      '1.5M tracked clicks',
      '3-year analytics retention',
      'Unlimited custom domains',
      'SSO + audit logs + SLA',
    ],
    featured: false,
    monthlyLinkLimit: 100000,
    trackedClicksLabel: '1.5M',
    customDomainsLabel: 'Unlimited',
    analyticsRetentionLabel: '3 years',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    badge: 'Custom everything',
    usd: 'Custom',
    cadence: '',
    seats: 'Unlimited users',
    cta: 'Talk to us',
    accent: 'linear-gradient(135deg, #7c3aed, #4f46e5)',
    description:
      "Need volumes beyond 100K links, dedicated infrastructure, custom SLAs, or white-labelling? Let's talk and build a plan around your exact needs.",
    features: [
      'Unlimited links',
      'Unlimited tracked clicks',
      'Custom analytics retention',
      'White-label & custom domains',
      'Dedicated support + custom SLA',
    ],
    featured: false,
    isCustomPricing: true,
    monthlyLinkLimit: Infinity,
    trackedClicksLabel: 'Unlimited',
    customDomainsLabel: 'Custom',
    analyticsRetentionLabel: 'Custom',
  },
];

export const billingPlanMap = new Map<SubscriptionPlanId, BillingPlanDefinition>(
  billingPlans.map((plan) => [plan.id, plan])
);

export const getBillingPlan = (planId: SubscriptionPlanId) =>
  billingPlanMap.get(planId) ?? billingPlanMap.get('free')!;

export const linkPacks: LinkPackDefinition[] = [
  {
    id: 'pack-100',
    name: 'Micro Pack',
    badge: 'Just getting started',
    price: '₹129',
    links: '100',
    cta: 'Buy 100 links',
    description:
      'A small top-up for occasional use. Great for trying out the platform or covering a one-off campaign without any commitment.',
    perks: [
      'Credits never expire',
      'No subscription required',
      'Stack on top of any plan',
    ],
    highlighted: false,
  },
  {
    id: 'pack-500',
    name: 'Starter Pack',
    badge: 'Most flexible',
    price: '₹499',
    links: '500',
    cta: 'Buy 500 links',
    description:
      'Enough for a product launch, seasonal campaign, or a few months of light use — all without locking into a monthly charge.',
    perks: [
      'Credits never expire',
      'No subscription required',
      'Stack on top of any plan',
    ],
    highlighted: false,
  },
  {
    id: 'pack-2000',
    name: 'Growth Pack',
    badge: 'Best value',
    price: '₹1,499',
    links: '2,000',
    cta: 'Buy 2,000 links',
    description:
      'The sweet spot for agencies and teams running periodic campaigns. Buy once, spread across projects, top up when needed.',
    perks: [
      'Credits never expire',
      'No subscription required',
      'Stack on top of any plan',
    ],
    highlighted: true,
  },
  {
    id: 'pack-10000',
    name: 'Bulk Pack',
    badge: 'High volume, no commitment',
    price: '₹4,999',
    links: '10,000',
    cta: 'Buy 10,000 links',
    description:
      "For large campaigns or platforms that spike in link creation but don't want a recurring bill. Use across months or years.",
    perks: [
      'Credits never expire',
      'No subscription required',
      'Stack on top of any plan',
    ],
    highlighted: false,
  },
];
